---
- name: "{{ role_name }} | {{ task.name }} | Update the PS1 environment variable to show git branches"
  ansible.builtin.blockinfile:
    path: "{{ user_env_file }}"
    backup: true
    block: |
      # Colors
      CYAN="\033[0;36m"
      GRAY="\033[90m"
      GREEN="\033[0;32m"
      PURPLE="\033[0;35m"
      RED="\033[0;31m"
      YELLOW="\033[0;33m"
      RESET="\033[0m"

      # Exit status color (green if success, red if fail)
      exit_status() {
        if [ $? -eq 0 ]; then
          printf "✔"
        else
          printf "($?)✘"
        fi
      }

      # Git branch and status
      parse_git_branch() {
        if git rev-parse --is-inside-work-tree &>/dev/null; then
          BRANCH=$(git branch --show-current 2>/dev/null)
          STATUS=$(git status --porcelain 2>/dev/null | wc -l)
          if [ $STATUS -eq 0 ]; then
            printf " (${BRANCH})"
          else
            printf " (${BRANCH}*)"
          fi
        fi
      }

      # Prompt format
      PS1="\[${CYAN}\]\u \[$GRAY\][\t] \[$GREEN\]\w \[$PURPLE\]\$(exit_status)\[$YELLOW\]\$(parse_git_branch)\[${RESET}\] \$ "
...
